[package]
name = "cqrs-es"
version = "0.2.0"
authors = ["Dave Garred <dave.garred@serverlesstechnology.com>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["cqrs", "event-sourcing", "serverless", "lambda"]
description = "A lightweight, opinionated CQRS and event sourcing framework targetting serverless architectures."
documentation = "https://docs.rs/cqrs-es"
repository = "https://github.com/serverlesstechnology/cqrs"
readme = "README.md"

[dependencies]
async-trait = "0.1.51"
serde = { version = "1.0.126", features = ["derive"]}
serde_json = "1.0.64"

[dev-dependencies]
static_assertions = "0.3"
tokio = { version = "1", features = ["macros", "rt"] }
uuid = { version = "0.8.2", features = ["v4"]}
