[package]
name = "cqrs-es"
version = "0.0.7"
authors = ["Dave Garred <dgarred@starbucks.com>"]
edition = "2018"
license-file = "LICENSE"
keywords = ["cqrs", "event-sourcing", "serverless", "lambda"]
description = "A lightweight, opinionated CQRS and event sourcing framework targetting serverless architectures."
repository = "https://github.com/serverlesstechnology/cqrs"
readme = "README.md"

[dependencies]
serde = { version = "1.0.104", features = ["derive"]}
serde_json = "1.0"
chrono = "0.4.11"
postgres = {version = "0.15.2", features = ["with-serde_json"]}

[dev-dependencies]
static_assertions = "0.3"
uuid = { version = "0.8", features = ["v4"]}